stages:
- name: Create Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: node
      pushRemote: true
      registry: demo.goharbor.io/seminario1
- name: Create Deployment
  steps:
  - applyYamlConfig:
      path: ./Deployment.yaml
timeout: 60
notification: {}