stages:
- name: Create Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: node
      pushRemote: true
      registry: index.docker.io
- name: Create Deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}