stages:
- name: Create Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: node
      pushRemote: true
      registry: docker login demo.goharbor.io -u pvasquezf -p V@squez12345
- name: Create Deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}