apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-vgxcx
    field.cattle.io/publicEndpoints: '[{"addresses":["34.68.244.41"],"port":3000,"protocol":"TCP","serviceName":"default:app1-loadbalancer","allNodes":false}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-app1
  name: app1
  selfLink: /apis/apps/v1/namespaces/default/deployments/app1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-app1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-01-02T04:46:53Z"
        field.cattle.io/ports: '[[{"containerPort":3000,"dnsName":"app1-loadbalancer","kind":"LoadBalancer","name":"3000tcp03","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-app1
    spec:
      containers:
      - image: demo.goharbor.io/seminario1/app1:latest
        imagePullPolicy: Always
        name: app1
        ports:
        - containerPort: 3000
          name: 3000tcp03
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
