apiVersion: beta1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-test
    spec:
      containers:
      - image: demo.goharbor.io/seminario1/node:proyecto
        imagePullPolicy: Always
        name: test
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker login demo.goharbor.io -u pvasquezf -p V@squez12345
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---      
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:default:test"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  labels:
    cattle.io/creator: norman
  name: nginx-loadbalancer
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-test
  type: LoadBalancer 

---
apiVersion: v1
data:
  password: V@squez12345
  username: pvasquezf
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: p-vlrzj-demogoharborio
  selfLink: /api/v1/namespaces/p-vlrzj-pipeline/secrets/p-vlrzj-demogoharborio
type: Opaque